/*
# Create SwachhLens operations workspace

1. New Tables
- `swachhlens_reports`: shared civic waste reports submitted to the workspace, including location, category, severity, duplicate count, workflow status, evidence, and resident-facing updates.
- `swachhlens_tasks`: operational work orders created from reports, including assigned crew, vehicle, ETA, completion evidence, verification score, and escalation state.

2. Security
- Row-level security is enabled on both tables.
- This first web dashboard is a single-tenant municipal workspace without sign-in, so anon and authenticated roles can read and manage the intentionally shared demo operations data.
- CRUD permissions are expressed as four separate policies per table.

3. Important Notes
- UUIDs and timestamps are generated by the database.
- Report and task records are linked with a foreign key so operational work cannot outlive its source report.
- The structure supports the plan's intake, duplicate/correlation, priority, dispatch, scheduling, verification, feedback, and escalation stages without requiring the citizen mobile app yet.
*/

CREATE TABLE IF NOT EXISTS public.swachhlens_reports (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  reference_code text NOT NULL UNIQUE,
  category text NOT NULL,
  location text NOT NULL,
  zone text NOT NULL DEFAULT 'Central',
  reported_at timestamptz NOT NULL DEFAULT now(),
  status text NOT NULL DEFAULT 'New',
  priority text NOT NULL DEFAULT 'Medium',
  severity_score integer NOT NULL DEFAULT 50,
  volume text NOT NULL DEFAULT 'Medium',
  hazard_flag boolean NOT NULL DEFAULT false,
  duplicate_count integer NOT NULL DEFAULT 1,
  confidence integer NOT NULL DEFAULT 90,
  description text NOT NULL DEFAULT '',
  resident_name text NOT NULL DEFAULT 'Resident',
  image_url text,
  citizen_update text NOT NULL DEFAULT 'Report received and queued for analysis.',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.swachhlens_tasks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  report_id uuid NOT NULL REFERENCES public.swachhlens_reports(id) ON DELETE CASCADE,
  task_code text NOT NULL UNIQUE,
  crew_name text NOT NULL,
  vehicle text NOT NULL,
  scheduled_for timestamptz NOT NULL DEFAULT now(),
  eta text NOT NULL DEFAULT '30 min',
  status text NOT NULL DEFAULT 'Assigned',
  completion_score integer,
  before_image_url text,
  after_image_url text,
  worker_note text NOT NULL DEFAULT '',
  escalated boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS swachhlens_reports_status_idx ON public.swachhlens_reports(status);
CREATE INDEX IF NOT EXISTS swachhlens_reports_priority_idx ON public.swachhlens_reports(priority);
CREATE INDEX IF NOT EXISTS swachhlens_reports_zone_idx ON public.swachhlens_reports(zone);
CREATE INDEX IF NOT EXISTS swachhlens_tasks_report_id_idx ON public.swachhlens_tasks(report_id);
CREATE INDEX IF NOT EXISTS swachhlens_tasks_status_idx ON public.swachhlens_tasks(status);

ALTER TABLE public.swachhlens_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.swachhlens_tasks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "workspace can read reports" ON public.swachhlens_reports;
CREATE POLICY "workspace can read reports" ON public.swachhlens_reports FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "workspace can create reports" ON public.swachhlens_reports;
CREATE POLICY "workspace can create reports" ON public.swachhlens_reports FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "workspace can update reports" ON public.swachhlens_reports;
CREATE POLICY "workspace can update reports" ON public.swachhlens_reports FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "workspace can delete reports" ON public.swachhlens_reports;
CREATE POLICY "workspace can delete reports" ON public.swachhlens_reports FOR DELETE TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "workspace can read tasks" ON public.swachhlens_tasks;
CREATE POLICY "workspace can read tasks" ON public.swachhlens_tasks FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "workspace can create tasks" ON public.swachhlens_tasks;
CREATE POLICY "workspace can create tasks" ON public.swachhlens_tasks FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "workspace can update tasks" ON public.swachhlens_tasks;
CREATE POLICY "workspace can update tasks" ON public.swachhlens_tasks FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "workspace can delete tasks" ON public.swachhlens_tasks;
CREATE POLICY "workspace can delete tasks" ON public.swachhlens_tasks FOR DELETE TO anon, authenticated USING (true);
